import Link from 'next/link';

export default function Home() {
  return (
    <main className="page">
      <div className="container home-hero">
        <h1 className="home-title">AI Generated Bedtime Stories</h1>
        <p className="home-subtitle">A new story every night, generated by OpenAI and delivered through Azure. During development you can also run this UI locally with mock data to keep costs at zero.</p>
        <Link href="/story?id=demo" className="home-cta">
          View sample story
        </Link>
      </div>
    </main>
  );
}
