// Shared Story Package types used across createStory, createCustomStory, generateImages, generateAudio and getStory.

export type SceneStatus = 'pending' | 'completed' | 'failed';

export type SceneType = 'cover' | 'introduction' | 'discovery' | 'adventure' | 'magicalMoment' | 'sleepEnding';

export interface CharacterSheet {
  name: string;
  appearance: string;
  visualConsistencyPrompt: string;
}

export interface TtsInstructions {
  voiceStyle: string;
  speed: string;
  pauses: string;
  emotion: string;
}

export interface StoryScene {
  sceneNumber: number;
  sceneType: SceneType | string;
  sceneTitle: string;
  sceneDescription: string;
  storySegment: string;
  startTime: string;
  endTime: string;
  startOffsetMs: number;
  endOffsetMs: number;
  imagePrompt: string;
  imageUrl: string;
  status: SceneStatus;
}

export interface StoryAudio {
  audioURL: string;
  durationSeconds: number;
  status: SceneStatus;
}

export interface StoryAssetsStatus {
  storyGenerated: boolean;
  audioGenerated: boolean;
  imagesGenerated: number;
  totalImages: number;
  completed: boolean;
}

// New recurring friends/places/magical elements introduced by this story, as reported by the LLM.
// Used to grow each character's persistent memory (see shared/childProfile.ts).
export interface MemoryUpdate {
  newFriends: string[];
  newPlaces: string[];
  newElements: string[];
}

// Full Story Package as generated by the LLM (before Cosmos persistence fields like id/ttl/createdAt are added).
export interface StoryPackage {
  title: string;
  estimatedDurationSeconds: number;
  characterSheet: CharacterSheet;
  story: string;
  description: string;
  ttsInstructions: TtsInstructions;
  scenes: StoryScene[];
  audio: StoryAudio;
  assetsStatus: StoryAssetsStatus;
  memoryUpdate: MemoryUpdate;
}

// Payload published on the StoryCreated Event Grid event.
export interface StoryCreatedEventData {
  id: string;
  title: string;
  story: string;
  description: string;
  scenes: StoryScene[];
  characterSheet: CharacterSheet;
  estimatedDurationSeconds: number;
}

// Payload published on the SceneImageRequested Event Grid event (Phase 3: one event per
// scene so generateSceneImage can run in parallel instead of looping sequentially).
export interface SceneImageRequestedEventData {
  storyId: string;
  sceneNumber: number;
  imagePrompt: string;
  characterSheet: CharacterSheet;
}

// Persistent, per-character memory (Phase 2) stored in the `childProfiles` Cosmos container.
// Keyed by a slug of the character name so the same character (e.g. "Vega") accumulates
// recurring friends/places/magical elements and a stable appearance across many stories.
export interface ChildProfile {
  id: string;
  name: string;
  appearance: string;
  recurringFriends: string[];
  recurringPlaces: string[];
  recurringElements: string[];
  storyIds: string[];
  createdAt: string;
  updatedAt: string;
}

export const SCENE_COUNT = 6;

export const SCENE_TEMPLATE: Array<{ sceneType: SceneType; startTime: string; endTime: string; startOffsetMs: number; endOffsetMs: number }> = [
  { sceneType: 'cover', startTime: '00:00', endTime: '00:15', startOffsetMs: 0, endOffsetMs: 15000 },
  { sceneType: 'introduction', startTime: '00:15', endTime: '00:35', startOffsetMs: 15000, endOffsetMs: 35000 },
  { sceneType: 'discovery', startTime: '00:35', endTime: '00:55', startOffsetMs: 35000, endOffsetMs: 55000 },
  { sceneType: 'adventure', startTime: '00:55', endTime: '01:15', startOffsetMs: 55000, endOffsetMs: 75000 },
  { sceneType: 'magicalMoment', startTime: '01:15', endTime: '01:35', startOffsetMs: 75000, endOffsetMs: 95000 },
  { sceneType: 'sleepEnding', startTime: '01:35', endTime: '02:00', startOffsetMs: 95000, endOffsetMs: 120000 },
];
